version: '3'
services:
  # react-ui-test:
  #   build: ../
  #   environment:
  #     - PORT=3000
  #   stdin_open: true
  #   # ports:
  #   #   - "9000:9000"
  #   # volumes:
  #   #   - .:/app
  #   #   - /app/node_modules # ensures we retain node_modules from docker build
  react-ui-test-wc:
    build: ../
    command: yarn start:wc
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    stdin_open: true

  cypress-wc:
    image: "cookiescrumbs/cypress-m1:9.4.1"
    depends_on:
      - react-ui-test-wc
    environment:
      - CYPRESS_baseUrl=http://react-ui-test-wc:9000
    working_dir: /e2e
    volumes:
      - ./:/e2e
