name: Build and Upload to S3

on:
  workflow_call:
    inputs:
      cookiebot_domain_group_id:
        required: false
        default: "1e9a6bdd-5870-4d54-8e5f-adcf6b5c5499"
        type: string
      deploy_dir:
        required: true
        type: string
      environment:
        required: true
        type: string
      public_url:
        required: true
        type: string
      react_app_api_endpoint:
        required: false
        default: "https://staging-editor-api.raspberrypi.org"
        type: string
      react_app_authentication_client_id:
        required: false
        default: editor-api
        type: string
      react_app_authentication_url:
        required: false
        default: "https://staging-auth-v1.raspberrypi.org"
        type: string
      react_app_login_enabled:
        required: false
        default: "true"
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_S3_BUCKET:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ENDPOINT:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.public_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path:
          - node_modules
          - .cache
        key: node_modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Build site and WC bundle
      run: |
        yarn build
        yarn build:wc
      env:
        COOKIEBOT_DOMAIN_GROUP_ID: ${{ inputs.cookiebot_domain_group_id }}
        PUBLIC_URL: ${{ inputs.public_url }}
        REACT_APP_API_ENDPOINT: ${{ inputs.react_app_api_endpoint }}
        REACT_APP_AUTHENTICATION_CLIENT_ID: ${{ inputs.react_app_authentication_client_id }}
        REACT_APP_AUTHENTICATION_URL: ${{ inputs.react_app_authentication_url }}
        REACT_APP_LOGIN_ENABLED: ${{ inputs.react_app_login_enabled }}

    - name: Deploy site to S3 bucket
      run: aws s3 sync  ./build/ s3://${{ secrets.AWS_S3_BUCKET }}/${{ inputs.deploy_dir }} --delete --endpoint ${{ secrets.AWS_ENDPOINT }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
