name: Test Upload

on:
  push:
    branches:
      -  main
      - 'feature/**'
      - 'issues/**'
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: eslint
      run: yarn lint

    - name: stylelint
      run: yarn stylelint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Run tests
      run: yarn test

  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
  
    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Build site and WC bundle
      run: |
        yarn build
        yarn build:wc

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Set bucket
        run: |
          if [ ${{ github.ref_type }} == 'tag' ]; then
            echo "Deploying to production bucket"
            echo "bucket=python-editor-dist-test" >> $GITHUB_ENV
          else
            echo "Deploying to staging/preview bucket"
            echo "bucket=python-editor-dist-test" >> $GITHUB_ENV
          fi
        shell: bash

    - name: Set deploy directory
        run: |
          if [ ${{ github.ref_type }} == 'tag' ]; then
            echo "Deploying tagged release ${{ github.ref_name }}"
            echo "deploy_dir=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ ${{ github.ref }} == 'refs/head/main' ]; then
            echo "Deploying staging release"
            echo "deploy_dir=staging" >> $GITHUB_ENV
          else
            echo "Deploying preview release ${{ github.ref_name }}"
            echo "deploy_dir=previews/${{ github.ref_name }}" >> $GITHUB_ENV
          fi
        shell: bash

    - name: Deploy site to S3 bucket
      run: aws s3 sync ./build/ s3://${{ env.bucket }}/${{ env.deploy_dir }} --delete
