name: Build and Upload to S3

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: eslint
      run: yarn lint

    - name: stylelint
      run: yarn stylelint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Run tests
      run: yarn run test --coverage --maxWorkers=4 --reporters=default --reporters=jest-junit
      env:
        JEST_JUNIT_OUTPUT_DIR: ./coverage/

    - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage

    - name: Record coverage
      run: ./.github/workflows/record_coverage
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        REF_NAME: ${{ github.ref_name }}

  test-cypress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        install: false
        start: |
          yarn start
          yarn start:wc
        wait-on: 'http://localhost:3000, http://localhost:3001'
      env:
        PUBLIC_URL: 'http://localhost:3000'

    - name: Archive cypress artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-artifacts
        path: |
          cypress/screenshots
          cypress/videos


  build-and-deploy-release:
    if: github.ref_type == 'tag'
    needs:
      - test
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      bucket: python-editor-dist-test
      deploy_dir: ${{ github.ref_name }}
      environment: production
      public_url: https://editor.raspberrypi.org/${{ github.ref_name }}
    secrets: inherit

  build-and-deploy-staging:
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      bucket: python-editor-dist-test
      deploy_dir: staging
      environment: staging
      # TODO: Trigger CF cache-busting job
      public_url: https://staging-editor.raspberrypi.org
    secrets: inherit

  build-and-deploy-preview:
    if: github.ref_type == 'branch' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      bucket: python-editor-dist-test
      deploy_dir: previews/${{ github.ref_name }}
      environment: previews/${{ github.ref_name }}
      # TODO: Place behind CF too, probably.
      public_url: http://python-editor-dist-test.s3-website.eu-west-2.amazonaws.com/previews/${{ github.ref_name }}
    secrets: inherit

