name: Build and Upload to S3

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: eslint
      run: yarn lint

    - name: stylelint
      run: yarn stylelint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Run tests
      run: yarn test

  test-cypress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install code
      run: yarn install --frozen-lock-file

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        install: false
        start: |
          yarn start
          yarn start:wc
        wait-on: 'http://localhost:3000, http://localhost:3001'
      env:
        PUBLIC_URL: 'http://localhost:3000'

    - name: Archive cypress artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-artifacts
        path: |
          cypress/screenshots
          cypress/videos


  build-and-deploy:release:
    if: github.ref_type == 'tag'
    needs:
      - test
    runs-on: ubuntu-latest
    uses: .github/workflows/build-and-deploy.yml
    with:
      aws-region: eu-west-2
      bucket: python-editor-dist-test
      deploy_dir: ${{ github.ref_name }}
      public_url: editor.raspberrypi.org
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-and-deploy:staging:
    if: github.ref == "refs/heads/main"
    needs:
      - test
    runs-on: ubuntu-latest
    uses: .github/workflows/build-and-deploy.yml
    with:
      aws-region: eu-west-2
      bucket: python-editor-dist-test
      deploy_dir: staging
      public_url: staging-editor.raspberrypi.org
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  build-and-deploy:preview:
    if: github.ref_type == "branch" && github.ref != "refs/heads/main"
    needs:
      - test
    runs-on: ubuntu-latest
    uses: .github/workflows/build-and-deploy.yml
    with:
      aws-region: eu-west-2
      bucket: python-editor-dist-test
      deploy_dir: previews/${{ github.ref_name }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

